version: "3.9"

services:
  mysql:
    image: mysql:8.1
    container_name: hexagon-mysql
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "shop"
      MYSQL_ROOT_PASSWORD: "test"
    restart: always
